#!/bin/sh

PASSWORD=$(date +%s)

sh $(pwd)/createlog.sh || exit 1
sh $(pwd)/installdependencies.sh >> /tmp/immich-install.log 2>&1 || exit 1
sh $(pwd)/configurepostgres.sh $PASSWORD >> /tmp/immich-install.log 2>&1 || exit 1
sh $(pwd)/createuser.sh >> /tmp/immich-install.log 2>&1 || exit 1
sh $(pwd)/createpaths.sh >> /tmp/immich-install.log 2>&1 || exit 1
sh $(pwd)/build.sh $PASSWORD >> /tmp/immich-install.log 2>&1 || exit 1
sh $(pwd)/installdaemons.sh >> /tmp/immich-install.log 2>&1 || exit 1
