#!/bin/sh

set -eux

# shellcheck disable=SC1091
. "$(pwd)/config.sh"

# Configure logging
install_logfile="/tmp/immich-install.log"
exec >> "$install_logfile" 2>&1

echo "Running postinstall as $(whoami)"

# Create immich user
"$(pwd)/createuser.sh"

# Create required directories
"$(pwd)/createpaths.sh"

# Build Immich application
"$(pwd)/build.sh"

# Install Launchd daemons
"$(pwd)/installdaemons.sh"
