#!/bin/sh

set -eu

# shellcheck disable=SC1091
. ./config.sh

install_logfile="/tmp/immich-install.log"
{
    ./createuser.sh
    ./createpaths.sh
    ./build.sh "$PASSWORD"
    ./installdaemons.sh
} 2>&1 | tee -a "$install_logfile"
