#!/bin/sh

set -eu

PASSWORD=$(date +%s)
echo "export PASSWORD=\"$PASSWORD\"" >> "$(pwd)/config.sh"

# shellcheck disable=SC1091
. "$(pwd)/config.sh"

install_logfile="/tmp/immich-install.log"
sh "$(pwd)/createlog.sh"
{
    sh "$(pwd)/installdependencies.sh"
    sh "$(pwd)/configurepostgres.sh" "$PASSWORD"
} >> "$install_logfile" 2>&1
