#!/bin/sh

set -eu

PASSWORD=$(date +%s)
echo "export PASSWORD=\"$PASSWORD\"" >> "./config.sh"

# shellcheck disable=SC1091
. "./config.sh"

install_logfile="/tmp/immich-install.log"
sh "./createlog.sh" "$install_logfile"
{
    sh "./installdependencies.sh"
    sh "./configurepostgres.sh" "$PASSWORD"
} 2>&1 | tee -a "$install_logfile"
