name: Immich macOS Package

on:
  # Trigger the workflow on pushes and pull requests to main branches
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  # Optionally, manually trigger the workflow
  workflow_dispatch:

jobs:
  build_pkg:
    name: Create Immich package for macOS
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Homebrew
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          brew install \
            node \
            npm \
            uv \
            vips

      # Step 4: Create Immich package
      - name: Create Immich package
        run: ./build_pkg.sh

      # Step 5: Release prebuilt package
      - name: Release prebuilt package
        uses: softprops/action-gh-release@v2
        with:
          files: "./output/Unofficial Immich Installer *.pkg"
