name: ShellCheck CI

on:
  # Trigger the workflow on pushes and pull requests to main branches
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Optionally, manually trigger the workflow
  workflow_dispatch:

jobs:
  lint:
    name: ShellCheck Linter
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install ShellCheck
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      # Run ShellCheck
      - name: Run ShellCheck
        run: |
          # Find all .sh files and run shellcheck on them
          find . -type f -name "*.sh" -exec shellcheck {} +
